#! /bin/python3

import sys, os, json

with open(sys.argv[1]) as f:
    data = json.load(f)

with open(os.path.splitext(os.path.split(sys.argv[1])[1])[0] + '.py', 'w') as f:
    print("#! /bin/python3\n# Code autogenerated from Jupyter notebook with a script. May contain errors.", file=f)
    for cell in data["cells"]:
        if cell['cell_type'] == "code":
            for code in cell["source"]:
                print(code.strip("\n"), file=f)
            print('', file=f)
